sonar.projectKey=UA-IPSS-Project_platform-frontend
sonar.organization=ua-ipss-project
sonar.projectName=Florinhas Digital - Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.js,**/*.test.js,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
